# Generated by Django 5.0.5 on 2024-05-30 13:54

import diem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0002_major_trainingpoint_quyche_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=20, null=True, verbose_name=diem.models.UserRole),
        ),
    ]
