# Generated by Django 5.0.5 on 2024-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpoint',
            name='QuyChe',
            field=models.ManyToManyField(to='diem.quyche'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(upload_to="'diem/%Y/%m"),
        ),
    ]
