# Generated by Django 5.0.1 on 2024-06-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0003_assistant_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='attended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
