# Generated by Django 5.0.1 on 2024-06-15 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0004_alter_registration_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='diem.activity'),
        ),
    ]
