# Generated by Django 5.0.5 on 2024-05-31 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0005_activity_alter_quyche_options_alter_student_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('point', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Quy Chế',
            },
        ),
        migrations.RemoveField(
            model_name='trainingpoint',
            name='QuyChe',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Hoạt Động Ngoại Khóa'},
        ),
        migrations.AlterModelOptions(
            name='trainingpoint',
            options={'verbose_name_plural': 'Điểm rèn luyện'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='TrainingPoint',
            new_name='trainingPoint',
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('trainingPoint', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='diem.trainingpoint')),
                ('statute', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='diem.statute')),
            ],
            options={
                'verbose_name_plural': 'Điểm',
                'unique_together': {('statute', 'trainingPoint')},
            },
        ),
        migrations.AddField(
            model_name='trainingpoint',
            name='statute',
            field=models.ManyToManyField(related_name='QuyChe', through='diem.Score', to='diem.statute'),
        ),
        migrations.DeleteModel(
            name='QuyChe',
        ),
    ]
