# Generated by Django 5.0.5 on 2024-05-31 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0006_statute_remove_trainingpoint_quyche_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingpoint',
            options={'verbose_name_plural': 'Bảng điểm rèn luyện'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='trainingPoint',
        ),
        migrations.AddField(
            model_name='trainingpoint',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='TrainingPoint', to='diem.student'),
        ),
    ]
