# Generated by Django 5.0.5 on 2024-05-31 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0007_alter_trainingpoint_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingpoint',
            old_name='diemTong',
            new_name='totalScore',
        ),
    ]
