# Generated by Django 5.0.5 on 2024-05-31 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0008_rename_diemtong_trainingpoint_totalscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name_plural': 'Điểm sinh viên theo từng quy chế'},
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='diem.class'),
        ),
    ]
