# Generated by Django 5.0.5 on 2024-06-02 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0009_class_alter_score_options_student_clas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='clas',
        ),
        migrations.AddField(
            model_name='class',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='diem.student'),
        ),
    ]
