# Generated by Django 5.0.5 on 2024-06-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0010_remove_student_clas_class_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Lớp'},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name_plural': 'Khoa'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='diem.class'),
        ),
    ]
