# Generated by Django 5.0.1 on 2024-06-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0012_score_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
    ]
