# Generated by Django 5.0.1 on 2024-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0014_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='statute',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
