# Generated by Django 5.0.1 on 2024-06-03 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0017_alter_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(limit_value=20.0), django.core.validators.MinValueValidator(limit_value=0.0)]),
        ),
    ]
