# Generated by Django 5.0.1 on 2024-06-10 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0020_rename_major_faculty_remove_student_major_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPointsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('proof', models.CharField(default=False, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, related_name='MissingPointsReport', to='diem.activity')),
                ('student', models.ForeignKey(default=False, on_delete=django.db.models.deletion.RESTRICT, related_name='MissingPointsReport', to='diem.student')),
            ],
            options={
                'verbose_name_plural': 'Danh Sách Báo Thiếu',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('attended', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registration', to='diem.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registration', to='diem.student')),
            ],
            options={
                'verbose_name_plural': 'Đăng kí Hoạt Động Ngoại Khóa',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='activity',
            field=models.ManyToManyField(related_name='student', through='diem.Registration', to='diem.activity'),
        ),
    ]
