# Generated by Django 5.0.1 on 2024-06-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0021_missingpointsreport_registration_student_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.ManyToManyField(through='diem.Registration', to='diem.activity'),
        ),
    ]
