# Generated by Django 5.0.1 on 2024-06-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diem', '0022_alter_student_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activity',
            field=models.ManyToManyField(related_name='student', through='diem.Registration', to='diem.activity'),
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('updated_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='achievements', to='diem.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
